"""Re-initialized migrations and re-added approver foreign key constraints

Revision ID: 925038652970
Revises: 
Create Date: 2025-06-29 00:08:55.460523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925038652970'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('driver_contact', sa.String(length=100), nullable=True),
    sa.Column('route_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('hall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dsa_approver_id', sa.Integer(), nullable=True),
    sa.Column('vc_approver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_event_created_by'),
    sa.ForeignKeyConstraint(['dsa_approver_id'], ['user.id'], name='fk_event_dsa_approver_id'),
    sa.ForeignKeyConstraint(['vc_approver_id'], ['user.id'], name='fk_event_vc_approver_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('pickup_time', sa.Time(), nullable=False),
    sa.Column('pickup_location', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('number_of_passengers', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('processed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['bus.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hall_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('processed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['hall_id'], ['hall.id'], ),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('ticket_id', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='fk_registration_event_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_registration_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration')
    op.drop_table('hall_booking')
    op.drop_table('bus_booking')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('hall')
    op.drop_table('bus')
    # ### end Alembic commands ###
