"""Add certificate_path to BusBooking model

Revision ID: 9dfe4f62c0c9
Revises: df8bc87a8a1f
Create Date: 2025-07-05 22:12:34.467472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfe4f62c0c9'
down_revision = 'df8bc87a8a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('certificate_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus_booking', schema=None) as batch_op:
        batch_op.drop_column('certificate_generated_at')
        batch_op.drop_column('certificate_path')

    # ### end Alembic commands ###
