"""Add certificate_path and certificate_generated_at to Registration

Revision ID: df8bc87a8a1f
Revises: 44f8441070c1
Create Date: 2025-06-30 01:38:49.533869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8bc87a8a1f'
down_revision = '44f8441070c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('certificate_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('certificate_generated_at')
        batch_op.drop_column('certificate_path')

    # ### end Alembic commands ###
